
import { EquipmentCategory, Condition, TransactionType, EquipmentListing, User } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'James Survey', email: 'james@example.com', role: 'seller', rating: 4.8, totalTransactions: 42, avatar: 'https://picsum.photos/seed/u1/100/100' },
  { id: 'u2', name: 'Sarah Eng', email: 'sarah@example.com', role: 'buyer', rating: 4.9, totalTransactions: 12, avatar: 'https://picsum.photos/seed/u2/100/100' },
  { id: 'admin', name: 'System Admin', email: 'admin@surveytrade.com', role: 'admin', rating: 5.0, totalTransactions: 0 }
];

export const MOCK_LISTINGS: EquipmentListing[] = [
  {
    id: 'l1',
    sellerId: 'u1',
    title: 'Leica TS16 P 1" R1000 Robotic Total Station',
    description: 'Highly accurate robotic total station for demanding engineering projects. Captures data automatically with dynamic lock technology.',
    category: EquipmentCategory.TOTAL_STATIONS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.BOTH,
    salePrice: 18500,
    rentalPriceDaily: 250,
    location: 'Accra, Greater Accra',
    images: ['https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Leica', 'Accuracy': '1"', 'EDM Range': '1000m', 'Type': 'Robotic' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l2',
    sellerId: 'u1',
    title: 'Trimble R12i GNSS RTK System',
    description: 'Top-of-the-line GNSS system with ProPoint technology and tip compensation. Works in the most challenging environments.',
    category: EquipmentCategory.GNSS_GPS,
    condition: Condition.LIKE_NEW,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 350,
    location: 'Kumasi, Ashanti',
    images: ['https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Trimble', 'Model': 'R12i', 'Tilt': 'IMU-based', 'Signals': 'Triple Frequency' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l3',
    sellerId: 'u1',
    title: 'Faro Focus S350 Laser Scanner',
    description: 'High-speed 3D laser scanner for rapid indoor and outdoor documentation. Range up to 350m.',
    category: EquipmentCategory.SCANNERS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.BOTH,
    salePrice: 28000,
    rentalPriceDaily: 600,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Faro', 'Scan Rate': '976k pts/sec', 'Range': '350m', 'Accuracy': '±1mm' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l4',
    sellerId: 'u2',
    title: 'DJI Matrice 350 RTK + Zenmuse L2',
    description: 'Professional aerial LiDAR surveying drone. The L2 sensor provides high-precision point clouds and RGB imagery.',
    category: EquipmentCategory.DRONES,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 15500,
    location: 'Takoradi, Western',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'DJI', 'Model': 'M350 RTK', 'Payload': 'Zenmuse L2', 'RTK': 'Integrated' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l5',
    sellerId: 'u1',
    title: 'Nikon NE-101 Digital Theodolite',
    description: 'Reliable and easy-to-use digital theodolite for construction and alignment tasks.',
    category: EquipmentCategory.THEODOLITES,
    condition: Condition.GOOD,
    transactionType: TransactionType.SALE,
    salePrice: 2200,
    location: 'Tamale, Northern',
    images: ['https://images.unsplash.com/photo-1579847513904-586737526978?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Nikon', 'Accuracy': '7"', 'Display': 'Dual LCD', 'Power': 'AA Batteries' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l6',
    sellerId: 'u2',
    title: 'Topcon GT-1200 Robotic Series',
    description: 'Ultra-fast ultrasonic motors provide the smoothest tracking in the industry. Optimized for one-man operations.',
    category: EquipmentCategory.TOTAL_STATIONS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 280,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1581092335397-9583ee92d0bb?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Topcon', 'Model': 'GT-1203', 'Motor': 'Ultrasonic', 'Tracking': '1000m' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l7',
    sellerId: 'u1',
    title: 'Leica DNA03 Digital Level',
    description: 'Highest precision digital level for 1st order leveling and subsidence monitoring.',
    category: EquipmentCategory.OPTICAL_LEVELS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.BOTH,
    salePrice: 7200,
    rentalPriceDaily: 120,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Leica', 'Precision': '0.3mm/km', 'Type': 'Digital', 'Memory': 'Included' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l8',
    sellerId: 'u2',
    title: 'Trimble TSC7 Data Collector',
    description: 'Rugged field tablet with 7-inch screen. Pre-loaded with Trimble Access 2024.',
    category: EquipmentCategory.OTHER,
    condition: Condition.LIKE_NEW,
    transactionType: TransactionType.SALE,
    salePrice: 3500,
    location: 'Kumasi, Ashanti',
    images: ['https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Trimble', 'OS': 'Windows 10', 'Connectivity': '4G/Wi-Fi', 'Durability': 'MIL-STD' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l9',
    sellerId: 'u1',
    title: 'Sokkia iM-105 Manual Total Station',
    description: 'Perfect entry-level manual station for site setting out. Bluetooth data transfer ready.',
    category: EquipmentCategory.TOTAL_STATIONS,
    condition: Condition.GOOD,
    transactionType: TransactionType.SALE,
    salePrice: 4800,
    location: 'Cape Coast, Central',
    images: ['https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Sokkia', 'Accuracy': '5"', 'Memory': '50,000 pts', 'Battery': '28 hrs' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l10',
    sellerId: 'u1',
    title: 'Heavy Duty Wooden Tripod (SECO)',
    description: 'Maximum stability for high-precision total stations and scanners. Vibration absorbing wood.',
    category: EquipmentCategory.TRIPODS_ACCESSORIES,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 450,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1516216628859-9bccecad13ef?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'SECO', 'Material': 'Maple Wood', 'Head': 'Flat', 'Weight': '7.5kg' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l11',
    sellerId: 'u2',
    title: 'CHCNAV i90 GNSS Receiver',
    description: 'Premium GNSS rover with integrated IMU for tilt-and-go surveying. Very reliable in urban areas.',
    category: EquipmentCategory.GNSS_GPS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.BOTH,
    salePrice: 8200,
    rentalPriceDaily: 180,
    location: 'Ho, Volta',
    images: ['https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'CHCNAV', 'Channels': '624', 'Tilt': '60 degrees', 'Battery': '10 hrs' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l12',
    sellerId: 'u1',
    title: 'Leica BLK360 Imaging Scanner',
    description: 'The world\'s smallest and lightest imaging laser scanner. High-resolution imagery combined with accurate point clouds.',
    category: EquipmentCategory.SCANNERS,
    condition: Condition.LIKE_NEW,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 450,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Leica', 'Weight': '1kg', 'Range': '60m', 'HDR': 'Supported' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l13',
    sellerId: 'u1',
    title: 'Spectra Precision LL300N Laser Level',
    description: 'Rugged self-leveling laser for construction. Includes HL450 receiver and tripod.',
    category: EquipmentCategory.LASER_LEVELS,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 1100,
    location: 'Koforidua, Eastern',
    images: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Spectra', 'Range': '500m', 'Self-Leveling': 'Automatic', 'Warranty': '5 Years' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l14',
    sellerId: 'u2',
    title: 'WingtraOne Gen II VTOL Drone',
    description: 'Professional vertical take-off mapping drone for large-scale mining and agriculture projects.',
    category: EquipmentCategory.DRONES,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 950,
    location: 'Sunyani, Bono',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Wingtra', 'Type': 'VTOL', 'Camera': 'Sony RX1RII', 'Coverage': 'Up to 400ha' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l15',
    sellerId: 'u1',
    title: 'South Galaxy G1 Plus GNSS',
    description: 'Compact and powerful GNSS system. Great value for money with Linux-based processing.',
    category: EquipmentCategory.GNSS_GPS,
    condition: Condition.GOOD,
    transactionType: TransactionType.SALE,
    salePrice: 3400,
    location: 'Wa, Upper West',
    images: ['https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'South', 'Channels': '336', 'Radio': 'Internal UHF', 'Weight': '970g' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l16',
    sellerId: 'u1',
    title: 'Leica GPR1 Circular Prism & Holder',
    description: 'High-quality circular prism with anti-reflex coating. Standard constant for Leica stations.',
    category: EquipmentCategory.TRIPODS_ACCESSORIES,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 320,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1516216628859-9bccecad13ef?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Leica', 'Accuracy': '2mm', 'Range': '3500m', 'Constant': '0.0mm' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l17',
    sellerId: 'u2',
    title: 'Topcon AT-B4A Optical Level',
    description: 'Standard 24x magnification optical level for site grading and foundations.',
    category: EquipmentCategory.OPTICAL_LEVELS,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 380,
    location: 'Bolgatanga, Upper East',
    images: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Topcon', 'Magnification': '24x', 'Accuracy': '2.0mm', 'Weight': '1.5kg' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l18',
    sellerId: 'u1',
    title: 'Carbon Fiber Rover Rod 2.5m',
    description: 'Lightweight and stiff telescoping pole with 40-minute vial. Snap-lock at 2.0m.',
    category: EquipmentCategory.TRIPODS_ACCESSORIES,
    condition: Condition.NEW,
    transactionType: TransactionType.SALE,
    salePrice: 280,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1516216628859-9bccecad13ef?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'SECO', 'Material': 'Carbon Fiber', 'Length': '2.5m', 'Vial': '40 min' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l19',
    sellerId: 'u2',
    title: 'Trimble S7 1" Vision Total Station',
    description: 'Integrated Trimble Vision for remote control and photographic documentation. MagDrive technology.',
    category: EquipmentCategory.TOTAL_STATIONS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 320,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1581092335397-9583ee92d0bb?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Trimble', 'Model': 'S7', 'Vision': 'Integrated', 'Servo': 'MagDrive' },
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'l20',
    sellerId: 'u1',
    title: 'Faro Swift Mobile Mapping System',
    description: 'High-speed mobile laser scanning. Capture large areas while walking.',
    category: EquipmentCategory.SCANNERS,
    condition: Condition.EXCELLENT,
    transactionType: TransactionType.RENTAL,
    rentalPriceDaily: 1200,
    location: 'Accra, Ghana',
    images: ['https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=800'],
    specs: { 'Brand': 'Faro', 'Type': 'Mobile', 'SLAM': 'Supported', 'Weight': 'Mobile Rig' },
    isApproved: true,
    createdAt: new Date().toISOString()
  }
];
